---

- name: Install nagios core requisites
  apt:
    name: 
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip

- name: add group nagcmd
  group:
    name: nagcmd
    state: present

- name: add user nagios
  user:
    name: nagios
    group: nagcmd
    
- name: download and extract nagios
  unarchive:
    src: https://sourceforge.net/projects/nagios/files/nagios-4.x/nagios-4.4.6/nagios-4.4.6.tar.gz
    dest: /tmp
    copy: no

- name: Configure nagios 
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.6

- name: Complie nagios make clean
  make:
    chdir: /tmp/nagios-4.4.6
    target: clean

- name: Compile nagios make all
  make:
    chdir: /tmp/nagios-4.4.6
    target: all

- name: Compile nagios make install
  make: 
    target: install
    chdir: /tmp/nagios-4.4.6

- name: Complie nagios make install-init
  make: 
     target: install-init
     chdir: /tmp/nagios-4.4.6

- name: Compile nagios make install-config
  make:
     target: install-config
     chdir: /tmp/nagios-4.4.6

- name: Compile nagios make install-commandmode
  make:
     target: install-commandmode
     chdir: /tmp/nagios-4.4.6

- name: Install webconf
  make:
     target: install-webconf
     chdir: /tmp/nagios-4.4.6

- name: Add web server to group
  ansible.builtin.user:
    name: www-data
    group: nagios

- name: a2enmod cgi
  command: a2enmod cgi

- name: Restart apache2
  service: 
      name: apache2
      state: restarted
      
- name: Install nagios plugins
  unarchive: 
    src: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure nagios plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-grou=nagcmd
  args:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make
  make:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make install
  make: 
    target: install
    chdir: /tmp/nagios-plugins-2.3.3

- name: Enable and start nagios
  service:
    name: nagios
    enabled: yes
    state: started
