galaxy_info:
  author: your name
  description: your role description
  company: your company (optional)

  lisence: lisence (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  galaxy_tags: []

  dependencies: []
