- name: installing components
  apt:
    name: rabbitmq-server
    state: latest

- name: start rabbitmq server
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: add user
  community.rabbitmq.rabbitmq_user:
    user: jelo
    password: jelo22
    state: present
