---
- hosts: centos 
  roles:
    - centos-elastic
    - centos-grafana
    - centos-lamp

- host: ubuntu 
  roles:
    - ubuntu-elastic
    - ubuntu-nagios 
    - ubuntu-nagios2
    - ubuntu-nagios3 
    - ubuntu-grafan 
    - ubuntu-lamp 

