---
- hosts: ubuntu
  become: true
  role:
    - ELK-U
    - Grafana-U
    - Nagios-U
    - Prometheus-U

- hosts: centos
  become: true
  roles:
    - ELK-U
    - Grafana-C
    - Nagios-C
    - Prometheus-C

    

