---
# tasks file for roles/ubuntu-MonitorInstall/grafana
name: add key to package
apt_key:
  url: https://packages.grafana.com/gpg.key
  state: present

name: add grafama repository
shell: echo "deb https:[ackages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/source.list.d/grafana.list

name: update ubuntu
apt:
  upgrade: 'yes'
  update_cache: yes

name: install grafana
apt:
  name: grafana
  state: present
