- name: Installing pre-requisites
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip

- name: Adding docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Setting up repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Installing docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Installing docker module for python
  pip:
    name: docker


