- name: install prerequisites
  apt:
  pkg:
    - python3
    - python3-pip
    - ca-certificates
    - gnupg
    - curl
    - lsb-release

- name: Docker's GPG key
  ansible.builtin.apt_key:
    url: https://download.dockert.com/linux/ubuntu/gpg
    state: present

- name: for repository
  ansible.builtin.apt_key:
  repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install docker-ce
  apt: 
    name: docker-ce
    state: latest
    update_cache: true

- name: install docker for python 
  pip: 
    name: docker
    state: latest
