---

- name: Install Grafana repository
  apt:
    deb: https://dl.grafana.com/lss/release/grafama_7.3.6_amd64.deb
    register: pkg_grafana

- name: dpkg grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: installing libfontconfig
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: installing grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: enabling grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

