---

- hosts: all
  become: true
  roles:
    - bind9

- hosts: all
  become: true
  roles:
    - dhcpd

- hosts: all
  become: true
  roles:
    - httpd_2

- hosts: all
  become: true
  roles:
    - mariadb

- hosts: all
  become: true
  roles:
    - samba

- hosts: all
  become: true
  roles:
    - vsftpd 

