ggit_repo: 'https://github.com/renzlaurennn/sysad2-2022/tree/prelim-exam'
git_dest: 'https://github.com/renzlaurennn/sysad2-2022.git'
git_ver: 'prelim-exam'

centos_vsftpd: centos_vsftpd/vsftpd.conf
debian_vsftpd: debian_vsftpd/vsftpd.conf
mageia_vsftpd: mageia_vsftpd/vsftpd.conf
  
name: ftpuser
password: password

motd: "Ansible Managed by mlplaurenciano-tip"

elasticsearch_hostname: elasticsearch
logstash_hostname: logstash
kibana_hostname: kibana
