---

- name: Install httpd
  dnf:
    name: httpd
    state: latest
    update_cache: yes

- name: Enable service to start on boot up
  service:
    name: httpd
    state: started

- name: Create firewall rule for apache service
  firewalld:
    service: http
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Restart apache service
  service:
    name: httpd
    state: restarted

- name: Install apache2-php5
  dnf:
    name: php
    state: latest
    update_cache: yes

