- name: install apache2 for centos
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: apache host index
  copy:
    content: "jelo is here"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index

- name: start and enable apache2 on centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: apache_index.changed

- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

