- name: Installing SQLDB
  apt:
    pkg:
      - mariadb-server
      - python3-pymysql

- name: Creating openstackcnf file
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch

- name: Adding details to openstackcnf file
  ansible.builtin.blockinfile:
    path: /etc/mysql/mariabdb.conf.d/99-openstack.cnf
    block: |
      [mysqld]
      bind-address = 10.0.2.15

      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = ut48_general_ci
      character-set-server = utf8

- name: Restarting mysql
  ansible.builtin.service:
    name: mysql
    state: restarted


