- name: Installing SQLDB
  apt:
    pkg:
    - mariadb-server
    - python3-pymysql


- name: Creating openstackcnf file
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch

- name: Adding details to openstackcnf file
  ansible.builtin.blockinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    block: |
      [mysqld]
      bind-address = 192.168.1.5
      
      default-storage-engine=innodb
      innodb_file_per_table=on
      max_connectiton=4096
      collation-server=utf8_general_ci
      character-set-server=utf8
- name: Resaring mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
