- name: install mysql-server
  yum: 
    name:
      - mariadb-server
      - mariadb
    state: latest
    update_cache: yes

- name: mysql host index
  copy:
    contents: "jelo is here"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  when: mysql_index.changed
