---

- name: Installing Dependencies
  yum:
    name:
      - python3
      - python3-pip

- name: Docker file
  yum:
    name: docker
    update_cache: yes
  register: docker

- name: Docker.py
  pip:
    name: docker.py
  when: docker.change
