---
- name: Install Filebeat with apt
  apt: 
  name: filebeat
  update_cache: yes

- name: Replace default filebeat.yml config
  template: 
   src: filebeat.yml.j2
   dest: /etc/filebeat/filebeat.yml

- name: Starting Filebeat
  service: 
   name: filebeat
   state: started


