- name: create interface
  file:
    path: /etc/network/interfaces
    state: touch


- name: configure interface
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto enp0s3
      iface  enp0s3 inet manual
      up ip link set dev $IFACE up
      down ip link set dev $IFACE down
      
- name: configure node hostname
  blockinfile:
    path: /etc/hosts
    block: |
      # controller
        192.168.100.7      controller

      # compute1
        192.168.100.4       compute1
