---
# task file for roles
- name: Installing Git for Centos
  yum:
    name: git
    state: latest

- name: Closing Prelim Exam branch
  git:
    repo: '{{ prelim-exam }}'
    dest: ./prelim-exam
    version: prelim-exam

