
---

- name: Update APT packages list

  apt:

    update_cache: yes

    cache_valid_time: 86400

- name: Install vsFTPd package

  apt:

    package: "{{ item }}"

    state: present

  with_items:

    - vsftpd

