---
- name: add grafana.repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/

- name: update centos
  yum:
    update_cache: yes

- name: install grafana
  yum:
    name: grafana
    state: present
