---

- name: Install prerequisites of elasticsearch
  apt:
    name:
      - openjdk-8-jdk
      - nginx
    state: latest
    update_cache: yes

- name: Get elasticsearch repo
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Get apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install elastic packages
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Install kibana
  apt:
    name: kibana
    update_cache: yes

- name: Install logstash
  apt:
    name: logstash
    update_cache: yes


