- name:
  yum:
    pkg:
      - mariadb
      - mariadb-server
      - python2-PyMySQL
   
- name: create openstack.cnf
  file:
    path: /etc/my.cnf.d/openstack.cnf
    state: touch
    
- name: insert bind address
  blockinfile:
    path: /etc/my.cnf.d/openstack.cnf
    block: | 
      [mysqld]
      bind-address = 192.168.100.4

      default-storage-engine = innodb
      innodb_file_per_table
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8
    
- name: enable mariadb
  service:
    name: mariabd
  state: started
  enabled: yes
     
