- name: Create Service Users
  ansible.builtin.command: "{{ item }}"
  with_items:
    - useradd --no-create-home --shell /bin/false prometheus
    - useradd --no-create-home --shell /bin/false node_exporter

- name: Creating local prometheus directories
  ansible.builtin.command: "{{ item }}"
  with_items:
    - mkdir /etc/prometheus
    - mkdir /var/lib/prometheus

- name: configuring prometheus
  ansible.builtin_get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux.amd64.tar.gz
    dest: /tmp/prometheus-2.0.0.linux-amd64.tar.gz
    mode: '0440'

- name: Unarchiving tar file
  ansible.builtin.unarchive:
    src: /tmp/prometheus-2.0.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Prometheus Two binaries
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: /tmp/
    with_items:
      - cp prometheus-2.0.0.linux-amd64/prometheus /usr/local/bin
      - cp prometheus-2.0.0.linux-amd64/promtool /usr/local/bin

- name: setting prometheus as owner of binaries
  ansible.builtin.command: "{{ item }}"
  with_items:
    - chown prometheus:prometheus /usr/local/bin/prometheus
    - chown prometheus:prometheus /usr/local/bin/promtool

- name: copying console and console libraries
  ansible: builtin.command: "{{ item }}"
  args:
    chdir: /tmp/
    with_items:
      - cp -r prometheus-2.0.0.linux-amd64/consoles /etc/prometheus
      - cp -r prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus
      - cp -r prometheus-2.0.0.linux-amd64/prometheus.yml /etc/prometheus

- name: setting prometheus as owner of console and console libraries
  ansible.builtin.command: "{{ item }}"
  with_items: 
    - chown -R prometheus:prometheus /etc/prometheus/consoles/
    - chown -R prometheus:prometheus /etc/prometheus/console_libraries/

- name: create prometheus service file
  copy:
    src: /root/activity7/roles/Prometheus-U/files/prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: delete
  ansible.builtin.command: rm -rf prometheus-2.0.0.linux-amd64.tar.gz prometheus-2.0.0.linux-amd64
  args:
    chdir: /tmp
