---
language: python 
pyhton: "2.7" 

sudo:false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible 
  - ansible --version 
  - printf '[defaults]\nroles_path=../'>ansible.cfg

script:
  - ansible-playbook tests.test.yml -i tests/inventory - -syntax-check

notification:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

