---
language: python
python: "2.7"
  
sudo: false

addons:
  apt:
    packages:
      - python-pip

Install:
  - pip install ansible
  - ansible --version
  - printf'[defaults]\nroles=../' >ansible.cfg

script:
  - ansible: https://galaxy.ansible.com/api/v1/notifications/

