- name: install prerequisites
  apt:
    pkg:
      - python3
      - pytho3-pip
      - ca-certificate
      - gnupg
      - curl
      - lsb-release

- name: Docker's GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: repository
  ansible.builtin.apt_key:
    repo: deb https://download.docker/linux/ubuntu/ focal table

- name: install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: install docker for python
  pip:
    name: docker
    state: latest
