- name: add gpg key
  apt_key:
    url: https://artifacts.elastic.co/GPG-key-elasticsearch
    state: present

- name: update ubuntu
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: install logstash
  apt:
    name: logstash
    state: present
    update_cache: yes

- name: install kibana
  apt:
    name: kibana
    state: present
    update_cache: yes
