---
language: python
python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible

  - ansible --version

  - printf '[defualt]\nroles_path=..\' >ansible.cfg

script:
  -ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notification:
  webhooks: https://galaxt.ansible.com/api/v1/notifications/

