---

name: install 
yum:
  name:
    - perl
    - gc
    - glibc
    - glibc-common
    - unzip
    - php
    - gd
    - gd-devel
    - postfix
    - compat-openss110
  state: present

name: add group 
group:
  name: naggroup
  state: present

name: add user
user:
  name: naguser
  group: naggroup

name: install nagios
unarchive:
  src: https://assets.nagios.com/download/nagioscore/release/nagios-4.4.5.tar.gz
  dest: /tmp
  remote_src: yes

name: configure nagios
command: ./configure --with-command-group=naggroup
args:
  chdir: /tmp/nagios-4.4.5

name: clean
make: 
  target: clean
  chdir: /tmp/nagios-4.4.5

name: make all
make:
  target: all
  chdir: /tmp/nagios-4.4.5

name: make install init
become: yes
make:
  target: install-init
  chdir: /tmp/nagios-4.4.5

name: make install-webconf
become: yes
make:
  target: install-webconf
  chdir: /tmp/nagios-4.4.5

name: install passlib
pip:
  name: passlib

name: create user in nagios
htpasswd:
  path: /usr/local/nagios/etc/htpasswd.users
  name: user
  passworkd: password

name: restart httpd
service:
  name: httpd
  state: restarted
  enable: yes
