- name: mariadb client
  command: mysql -u root -p
  
- name: create database in client
  command: CREATE DATABASE keystone;
   
- name: grant access
  command:
    argv:
      - GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'ged156435';
      - GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY 'ged156435';
      
- name: exit client
  command: exit

- name: install pre requisites
  yum:
    pkg:
      - openstack-keystone
      - httpd
      - mod_wsgi
    state: latest
    
- name: Insert connection to database
   blockinfile:
    path: /etc/keystone/keystone.conf
    insertafter: "[database]"
    block: |
      # ...
      connection = mysql+pymysql://keystone:KEYSTONE_DBPASS@controller/keystone
      
- name: Insert connection to token
  blockinfile:
    path: /etc/keystone/keystone.conf
    insertafter: "[token]"
    block: |
      # ...
      provider = fernet
        
- name: populate identity service
  command:  su -s /bin/sh -c "keystone-manage db_sync" keystone
    
- name: Initialize Fernet key repositories
  command:
    argv:
      - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
      
- name: bootstrap identity service
  command: keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

- name: edit server name of port
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '# ServerName gives the name and port that the server uses to identify itself'
    line: ServerName controller
    
- name: start httpd service
  service:
    name: httpd
    state: started
    enabled: yes

    
    
 
