---
 - name: Import
   apt_key:
     baseurl: https://artifacts.elstic.com/GPG-KEY-elasticsearch 
     state: present 

 - name: ADding elastic APT repository 
   apt_repository: 
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable

main 
   state: present 
   filename: elastic-7.x.list 
   update_cache: yes 

   - name: install elasticsearch
     apt:
       name: elasticsearch
       state: present
       update_cache: yes 

   - name: reload systemd config 
     systemd: daemon_reload=yes

   - name: enabled service elasticsearch and ensure it 
     systmed:
       name: elasticsearch 
       enabled: yes
       masked: no 

   - name: ensure elasticsearch is running
     systmed: state=started name=elasticsearch 

  
