---
# tasks file for gitclone_centos
- name: CREATE DIRECTORY
  file:
    path: /home/mjlrhabla-tip/repo
    state: directory
    mode: '777'

- name: INSTALL GIT
  yum:
    name: git
    state: latest
    update_cache: yes

- name: CLONE PRELIM EXAM
  git:
    repo: 'https://github.com/mjlrhabla-tip/sysad2-2022.git'
    dest: /home/mjlrhabla-tip/repo
    version: prelim-exam
    clone: yes
    update: yes
