- name: install prometheus
  ansible.builtin.get.url:
    url: https://github.com/prometheys/prometheys/releases/doownload/0.16.0/prometheus-0.16.0.linux-amd64.tar.gz
    dest: /home/gllaus-tip/prometheus-0.16.0.linux-amd64.tar.gz
    mode: '0440'

- name: create directory
  ansible.builtin.command: mkdir /home/gllaus-tip/Prometheus

- name: unarchiving
  ansible.builtin.unarchive:
    src: /home/gllaus-tip/prometheus-0.16.0.linux-amd64.tar.gz
    dest: /home/gllaus-tip/Prometheus
    remote_src: yes

