- name: creating block file
  file:
    path: /etc/yum.repos.d/influxdb.repo
    state: touch

- name: adding details
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/influxdb.repo
    block: |
      [influxdb]
      name = InfluxDB Repository - RHEL \$releasever
      baseurl=https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=1
      gpgkey=https://repos.influxdata.com/influxdb.key
      EOF

- name: Installing influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes

