- name: add repository for grafana
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/

- name: install grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes

- name: start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: add repository for prometheus
  copy:
    src: prometheus.repo
    dest: /etc/yum..repos.d

- name: install prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: start and enable prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: add repo for influxdb
  copy:
    src: influxdb.repo
    dest: /etc/yum/repos.d/

- name: add repo key influx.db
  rpm_key:
    key: https://repos.influxdata.com/influxdb.key
    state: present

- name: install influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes

- name: start and enable influxdb
  service:
    name: influxdb
    state: started
    enabled: yes
