--- 

- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: latest
  update_cache: yes

- name: Start Mysql service
  service:
    name: mysql
    state: started
    enabled: true

- name: Install mysql extension for PHP
  apt:
    name: php5-mysql
    state: latest
  update_cache: yes

- name: Restart Apache
  service:
    name: apache2
    state: restarted


