- name: installing prerequisites
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common 
    - wget

- name: getting Grafana Key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Adding to Repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Installing Grafana
  apt:
    name: grafana
    update_cache: yes
