---
- name: download and extract nagios
  unarchive:
    src: https://sourceforge.net/projects/nagios/files/nagios -4.x/nagios -4.4.6.tar.gz
    dest: /tmp
    copy: no

- name: configure nagios
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios -4.4.6

- name: compile nagios make clean
  make:
    chdir: /tmp/nagios -4.4.6
    target: clean

- name: compile nagios make all
  make:
    chdir: /tmp/nagios -4.4.6
    target: all

- name: compile nagios make install
  make:
    target: install
    chdir: /tmp/nagios -4.4.6

- name: compile nagios make install-init
  make:
    target: install-init
    chdir: /tmp/nagios -4.4.6

- name: compile nagios make install-config
  make:
    target: install-config
    chdir: /tmp/nagios -4.4.6

- name: compile nagios make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios -4.4.6

- name: install webconf
  make:
    target: install-webconf
    chdir: /tmp/nagios -4.4.6

- name: add user account
  htpasswd:
    path: /usr/local/nagios/etc/htpass.users
    name: "{{user}}"
    password: "{{pass}}"

- name: a2enmod cgi
  command: a2enmod cgi

- name: restart apache2
  service:
    name: apache2
    state: restarted
