---
#- name: CentOS
#hosts:
#- centos
#vars_files:
#- config.yaml
#roles:
    #- centos-prelim
    #- centos-ftp
    #- centos-motd
    #- centos-nagios

- name: Ubuntu
  become: true
  hosts:
      - ubuntu
  vars_files:
      - config.yaml
  roles:
      - ubuntu-prelim
      - ubuntu-ftp
      - ubuntu-motd
      - ubuntu-nagios

      #- name: Debian
      #hosts:
      #- debian
      #vars_files:
      #- config.yaml
      #roles:
      #- debian-prelim
      #- debian-ftp
      #- debian-motd
      #- debian-nagios
