---
- name: CentOS
  hosts:
    - centos
  vars_files:
    - config.yaml
  roles:
    - centos-clone
    - centos-ftp
    - centos-motd
    - centos-nagios

- name: Ubuntu
  hosts:
    - ubuntu
  vars_files:
    - config.yaml
  roles:
    - ubuntu-clone
    - ubuntu-ftp
    - ubuntu-motd
    - ubuntu-nagios

- name: Debian
  hosts:
    - debian
  vars_files:
    - config.yaml
  roles:
    - debian-clone
    - debian-ftp
    - debian-motd
    - debian-nagios
