--- 
language: python
python: "2.7"
sudo: false
addons:
  apt:
    packages:
      - python-pip
install:
   - pip isntall ansible
   - ansible -- version
   - printf '[defaults]\nroles_pat=../'>ansible.cfg 

script:
  - ansibel-playbook tests.test.yml -i test/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/


