---
- name: install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: add apache_index
  copy:
    content: "Apache test"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
    register: apache_index

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
    when: apache_index.changed

- name: whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: install mysql
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: add mysql_index
  copy:
    content: "MYSQL test"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
    register: mysql_index

- name: run mysql
  service:
    name: mysql
    state: started
    enabled: yes
    when: mysql_index.changed

- name: install php
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: add php_index
  copy:
    content: "PHP test"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
