- name: instll mariadb server
  apt:
    pkg:
      - mariadb-server
      - python3-pymysql

- name: create openstack.cmf
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch 

- name: edit openstack.cmf
  ansible.builtin.blockinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    block: |
      [mysqld]
      bind-address = 192.168.122.11

      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8

- name: restart mysql 
  ansible.builtin.service:
    name: mysql
    state: restarted
