---
- name: Adding APT repository
 apt_repository:
   repo: deb  https://artifacts.elastic.co/packages/7.x/apt  stable main
   state: present

- name: Update repositories cache and install Logstash
  apt:
   name: logstash
   update_cache: yes

- name: Configure logstash.yml File
  copy:
    src: /path/to/your/logstash.yml
    dest: /etc/logstash/logstash.yml

- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes

- name: Start Logstash service
  systemd:
    name: logstash
    state: started
    daemon_reload: yes
