---

- hosts: all
  become: true
  tasks:
    - name: Install nagios core
      apt:
        pkg:
          - wget
          - unzip
          - openssl
          - build-essential
          - libgd-dev
          - libssl-dev
          - libapache2-mod-php
          - php-gd
          - php
          - apache2
    
    - name: Download nagios core setup
      ansible.builtin.command: wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz

    - name: extract download
      ansible.builtin.command: sudo tar -zxvf nagios-4.4.6.tar.gz

    - name: navigate directory
      ansible.builtin.command: "sudo ./configure"
      args:
        chdir: "nagios-4.4.6"

    - name: compile main program and cgi
      ansible.builtin.command: "sudo make all"
      args:
        chdir: "nagios-4.4.6"

    - name: install and make group user
      ansible.builtin.command: "sudo make install-groups-users"
      args:
        chdir: "nagios-4.4.6"

    - name: add www-data directories
      ansible.builtin.command: "sudo usermod -a -G nagios www-data"
      args:
        chdir: "nagios-4.4.6"

    - name: Install Nagios
      ansible.builtin.command: "sudo make install"
      args:
        chdir: "nagios-4.4.6"

    - name: initialize all installation and configuration scripts
      ansible.builtin.command: "sudo make install-init"
      args:
        chdir: "nagios-4.4.6"

    - name: Install permission on config direc
      ansible.builtin.command: "sudo make install-commandmode"
      args:
        chdir: "nagios-4.4.6"

    - name: install sample config file
      ansible.builtin.command: "sudo make install-config"
      args:
        chdir: "nagios-4.4.6"

    - name: Install apache file
      ansible.builtin.command: "sudo make install-webconf"
      args:
        chdir: "nagios-4.4.6"

    - name: enable apache rewrite mode
      ansible.builtin.command: "sudo a2enmod rewrite"
      args:
        chdir: "nagios-4.4.6"

    - name: enable cgi conf
      ansible.builtin.command: "sudo a2enmod cgi"
      args:
        chdir: "nagios-4.4.6"

    - name: restart apache service
      ansible.builtin.command: "sudo systemctl restart apache2"
      args:
        chdir: "nagios-4.4.6"

    - name: download nagios core plugin
      ansible.builtin.command: wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz

    - name: Extract downloaded plugin
      ansible.builtin.command: sudo tar -zxvf nagios-plugins-2.3.3.tar.gz

    - name: run plugin configure
      ansible.builtin.command: "sudo ./configure --with-nagios-user=nagios --with-nagios-group=nagios"
      args:
        chdir: "nagios-plugins-2.3.3/"

    - name: compile nagios core plugin
      ansible.builtin.command: "sudo make"
      args:
        chdir: "nagios-plugins-2.3.3/"

    - name: install plugins
      ansible.builtin.command: "sudo make install" 
      args:
        chdir: "nagios-plugins-2.3.3/"
