- name: management enterprise services

    role_name: dhcpd
    hosts: all
    become: true
    roles:
      - dhcpd

    role_name: bind9
    hosts: all
    become: true
    roles:
      - bind9

    role_name: vsftpd
    hosts: all
    become: true
    roles:
      - vsftpd

    role_name: samba
    hosts: all
    become: true
    roles:
      - samba

    role_name: httpd
    hosts: all
    become: true
    roles:
      - httpd

    role_name: mariadb
    hosts: all
    become: true
    roles:
      - mariadb

