- name: Creating Service Users
  ansible.builtin.command: "{{ item }}"
  with_items:
    - useradd --no-create-home --shell /bin/false prometheus
    - useradd --no-create-home --shell /bin/false node_exporter

- name: Creating Local prometheus directories
  ansible.builtin.command: "{{ item }}"
  with_items:
    - mkdir /etc/prometheus
    - mkdir /var/lib/prometheus

- name: Setting prometheus as owner of local prometheus directories
  ansible.builtin.command: "{{ item }}"
  with_items:
    - chown prometheus:prometheus /etc/prometheus
    - chown prometheus:prometheus /var/lib/prometheus

- name: Downloading Prometheus tar from Prometheus repository
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.0.0.linux-amd64.tar.gz
    mode: '0440'

- name: Unarchiving tar file
  ansible.builtin.unarchive:
    src: /tmp/prometheus-2.0.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copying two binaries to prometheus local directory
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: /tmp/
  with_items:
    - cp prometheus-2.0.0.linux-amd64/prometheus /usr/local/bin/
    - cp prometheus-2.0.0.linux-amd64/promtool /usr/local/bin/

- name: Setting prometheus as owner of the two binaries
  ansible.builtin.command: "{{ item }}"
  with_items:
    - chown prometheus:prometheus /usr/local/bin/prometheus
    - chown prometheus:prometheus /usr/local/bin/promtool

- name: Copying consoles and console libraries to prometheus directory
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: /tmp/
  with_items:
    - cp -r prometheus-2.0.0.linux-amd64/consoles /etc/prometheus
    - cp -r prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus
    - cp -r prometheus-2.0.0.linux-amd64/prometheus.yml /etc/prometheus

- name: Setting Prometheus as owner of consoles and console libraries 
  ansible.builtin.command: "{{ item }}"
  with_items:
    - chown -R prometheus:prometheus /etc/prometheus/consoles
    - chown -R prometheus:prometheus /etc/prometheus/console_libraries

- name: Creating prometheus service file
  copy:
    src: /root/sysad2-2022/activity7/roles/Prometheus/files/prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: cleaning up
  ansible.builtin.command: rm -rf prometheus-2.0.0.linux-amd64.tar.gz prometheus-2.0.0.linux-amd64
  args:
    chdir: /tmp/
