- name: Installing apache
  apt:
    name: apache2
    update_cache: yes

- name: Installing mysql-server
  apt:
    name: mysql-server
    update_cache: yes

- name: Installing PHP
  apt: 
    name: php
    update_cache: yes

- name: Installing libapache
  apt:
    name: libapache2-mod-php
    update_cache: yes

- name: Installing php-mysql
  apt:
    name: php-mysql
    update_cache: yes
