---
language: python
python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - pytho-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[default]\roles_path=../' >ansible.cfg

script: 
  - ansible-playbook tests/test/yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

