---
- hosts: lampstack
- name: Installing lamp stack
  apt:
    pkg:
    - apache2
    - mysql-server
    - php
    - libapache2-mod-php
    - php-mysql
  update_cache: yes
  
  - name: Getting apt key
    ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Adding to repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu bionic stable
    state: present

- name: Installing influxdb
  apt:
    name: influxdb
    update_cache: yes
