prelim_exam: https://github.com/apayor-tip/sysad2-2022.git
username: apayor-tip
writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"
ftp:debian: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"
ftp_user: apayor
ftp_pass: 123
naguser_pass: apayor
nagadmin_pass: 123
