- name: install memcached
  yum:
    name: memcached
    state: latest

- name: install python-memcached
  yum:
    name: python-memcached
    state: latest

- name: edit memcached
  lineinfile:
    path: /etc/sysconfig/memcached
    regexp: 'OPTIONS='
    line: OPTIONS="-1 192.168.1.0,::1,controller"

- name: start memcached
  service:
    name: memcached
    state: latest
    enabled: yes
