- name: install prerequisite
  apt:
    pkg:
      - mariadb-server
      - python3-pymysql
      - apache2
    update_cache: yes

- name: start mysql
  ansible.builtin.service:
    name: mysql-server
    state: started

- name: create keystone db
  community.mysql.mysql_db:
    name: Keystone
    state: present

- name: grant access to keystone db
  community.mysql.mysql_query:
    login_db: Keystone
    query: GRANT ALL PRIVILEGES ON keystone.* TO 'root'@'localhost' IDENTIFIED BY 'awtsgege';

- name: grant access to keystone db 2
  community.mysql.mysql_query:
    login_db: Keystone
    query: GRANT ALL PRIVILEGES ON keystone.* TO 'root'@'%' IDENTIFIED BY 'awtsgege';

- name: install keystone
  apt:
    name: keystone
    update_cache: yes

- name: edit keystone.conf file
  ansible.builtin.lineinfile:
    path: /etc/keystone/keystone.conf
    regexp: connection = sqlite:////var/lib/keystone/keystone.db
    line: connection = mysql+pymysql://keystone:awtsgege1@controller/keystone

- name: configure provider
  ansible.builtin.lineinfile:
    path: /etc/keystone/keystone.conf
    regexp: #provider = fernet
    line: provider = fernet

- name: populate identity service db
  ansible.builtin.command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: initialize fernet key repo
  ansible.builtin.command: "{{ item }}"
  with_items:
    - keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    - keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: bootstrap identity service
  ansible.builtin.command: keystone-manage bootstrap --bootstrap-password awtsgege --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:500/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

- name: configure http server
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    line: ServerName controller
    state: present

- name: restarting apache
  ansible.builtin.service:
    name: apache2
    state: restarted

