---
language: python
python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:

  - pip install ansible

  - ansible --version

  - printf '[default]\nroles_path../' >ansible.cfg

script:
  - ansible-playboo tests/test.yml -i test/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

