--- 
- name: add grafana repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/

- name: Install grafana
  yum: 
  name: grafana
  state: latest
  update_cache: yes

- name: Run grafama
  service:
    name: grafana-server
    state: started

- name: Add prometheus erpo
  copy:
    src: prometheus.repo
    dest: /etc/yum.repos.d

- name: Install prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: Run prometheus
  service:
  name: prometheus
  state: started

- name: Add influxdb repo
  copy: src: influxdb.repo
  dest: /etc/yum.repos.d/

- name: Install influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes

- name: Run influxdb
  service:
    name: influxdb
    state: started
    










