- name: install prerequisites
  apt:
    pkg:
      - python3
      - python3-pip
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: get gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: setting up repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  

- name: install docker.py
  pip:
    name: docker.py
    state: latest
