- name: Installing Git 
  apt:
    name: git
    state: latest

- name: Cloning Prelim Exam branch
  git:
    repo: 'https://github.com/mgascuevas-tip/sysad2-2022.git'
    dest: /home/gedrei/sysad2-2022/prelim-exam
    version: prelim-exam
