- name: Installing prerequisites
  yum:
    name: java-1.8.0-openjdk
    update_cache: yes

- name: Installing elastic stack public signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Create file repo
  file:
    path: /etc/yum.repos.d/elasticsearch.repo
    state: touch

- name: Creating file repo for nginx
  file:
    path: /etc/yum.repos.d/nginx.repo
    state: touch

- name: Inserting repo info
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/elasticsearch.repo
    block: |
      [elasticsearch-6.x]
      name=Elasticsearch repository for 6.x packages
      baseurl=https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enalbed=1
      autorefresh=1
      ttype=rpm-md

- name: Inserting nginx repo info
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/nginx.repo
    block: |
      [nginx]
      name=nginx repo
      baseurl=https://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=0
      enabled=1


- name: Installing Elastic Stack
  yum:
    pkg:
      - elasticsearch
      - kibana
      - logstash
      - filebeat
      - nginx
    state: present
    update_cache: yes

- name: Creating config file
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#bootstrap.memory_lock: true'
    line: 'bootstrap.memory_lock: true'

- name: Configuring localhost
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#network.host: 192.168.0.1'
    line: 'network.host: localhost'

- name: Configuring Port
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#http.port:9200'
    line: 'http.port:9200'

- name: Configuring elasticsearch config
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/elasticsearch
    regexp: '#MAX_LOCKED_MEMORY=unlimited'
    line: 'MAX_LOCKED_MEMORY=unlimited'

- name: Configuring Kibana
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '#server.port: 560'
    line: 'server.port: 5601'

- name: Configuring host Kibana
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '#server.host: "localhost"'
    line: 'server.host: "123.234.123.234"'

